Feat/Fix: mrgnhnt96
mrgnhnt96/autoequal pull request #11
Opened 2022-10-26 20:51 UTC by mrgnhnt96

Hey @SunnyDayDev!

This is a large PR, if you'd like for me to break it into smaller PRs, I definitely can.

Here is a breakdown of the PR:

## Features

- Allow abstract classes
  - totally understand your reasoning in #5, but I think that this is a good feature to have. The developers that use this package should have an understanding of what they are doing. If they want to generate the props for an abstract class, which will more than likely be re-used in subclasses, then they should be able to.
- Check for Inheritance
  - If a class extends another class that uses Equatable, then the props will be generated without the need of extending Equatable or using the mixin EquatableMixin.
    - This was not an issue if the super class extended Equatable, but not if the super class used the mixin.
  - This also allows for super prop generation for `autoequalMixin` classes.
- Auto handle mixins
  - If a class uses the mixin EquatableMixin, then the props will be generated without the need of annotating with `@autoequalMixin`.
    - The class can continue to be annotated with `autoequalMixin` to force the generation of the autoequal mixin.
- Change `_autoequalProps` to `_$props`
  - This change is to follow generation convention, by including the leading underscore and the trailing dollar sign.
    - `_autoequalProps` is still supported, annotated with `@Deprecated`. Which can be removed in a future release.
- Additional field checks
  - Check to see if the field has a getter
    - If none, the field will be ignored.
    - Fixes #10
  - Check for synthetic fields
    - If the field is a getter, then it will be ignored.
      - Unless the field is annotated with `@includeAutoequal`.
    - Fixes #9
- Add global option to include/ignore getter methods
  - Fixes #10
  - Within the `build.yaml` file, the following option is supported

```yaml
targets:
  $default:
    builders:

      autoequal_gen:
        enabled: true
        options:
          include_getters: true # default is false
```

- Add scope to exports
  - Currently all classes and constants are exported from `autoequal`. By adding a scope, we can reduce the possible dev confusion of having multiple options
    - Only export the following
      - `autoequal`
      - `autoequalMixin`
      - `includeAutoequal`
      - `ignoreAutoequal`
- Add Targets to annotation classes
  - Helps the analyzer to determine where the annotation can be used.
    - `autoequal` can only be used on classes
    - `autoequalMixin` can only be used on classes
    - `includeAutoequal` can only be used on fields & getters
    - `ignoreAutoequal` can only be used on fields & getters
- Change builder name from `autoequal` to `autoequal_gen`
  - This is to follow the convention of other builders, such as `json_serializable` and `freezed`.
  - by keeping the builder name the same as the project, configuring the build.yaml file is simpler
    - Current config: `autoequal_gen|autoequal`
    - New config: `autoequal_gen`
- Add warnings when `props` method is not implemented
  - This warning is printed to console only when annotated with `@autoequal` and
    - extending `Equatable` and props is not implemented
    - inheriting from a class that uses `Equatable` and props is not implemented
- Add Tests
  - The previous test files were only testing the work of equatable and not so much of the generated code. So I re-wrote the tests to test each case individually for extends, extends with mixin, and mixin only scenarios.
    - Use cases
      - abstract
      - basic
      - getter
      - ignore
      - include getter
      - inherited
      - inherited none
      - private
      - setter
- Update README
  - Update the README to reflect the changes made in this PR.

I know this is a lot, so please let me know if you have any questions or concerns. I'm happy to make any changes that you would like.

2022-10-27 03:34 UTC, SunnyDayDev commented
Hey @mrgnhnt96!
I'm too busy on weekdays so I'll check the PR on the weekend.

I'm in anticipation, it seems to be a great work.

2022-10-29 09:30 UTC, SunnyDayDev commented
Hey @mrgnhnt96!
I checked the PR. You have done the excellent work!

Most of changes are great and good quality. With the exception of the moment which we have to discuss.

2022-10-29 09:31 UTC, SunnyDayDev commented
What you think, is it a good idea to change the API? I mean the renaming `_autoequalProps` to `_$props`.

Why the `_$props` is better than `_autoequalProps`? Is it just shorter or  better fits the dart/flutter code convention?

2022-10-29 09:55 UTC, SunnyDayDev requested changes
Hey @mrgnhnt96!
I checked the PR. You have done the excellent work!

Most of changes are great and good quality. With the exception of these small issues.

2022-10-29 09:55 UTC, SunnyDayDev commented on test_project/lib/extends/getter.dart
> +  set one(String newValue) => print(newValue);
It seems that it should be getter instead of a setter

```suggestion
  String get one => 'one';
```

2022-10-29 09:55 UTC, SunnyDayDev commented on test_project/lib/extends_with_mixin/getter.dart
> +  set one(String newValue) => print(newValue);
Same here. It seems that it should be getter instead of a setter

```suggestion
  String get one => 'one';
```

2022-10-29 09:55 UTC, SunnyDayDev commented on test_project/lib/mixin/getter.dart
> +  set one(String newValue) => print(newValue);
And this one.

```suggestion
  String get one => 'one';
```

2022-10-29 10:06 UTC, SunnyDayDev commented
I like the way that you solved mentioned issues. You even added the ability to use abstract classes in a good way, so I'm ready to agree that it's a necessary feature.

2022-10-29 13:50 UTC, mrgnhnt96 commented
😅 Nice catches, those have been fixed and pushed to the branch 👍

2022-10-30 08:09 UTC, SunnyDayDev approved these changes
Now it's quite good)

2022-10-30 08:10 UTC, merged

2022-10-30 08:12 UTC, SunnyDayDev commented
I'll update CHANGELOG, set up CI to run tests with the new test project, and then publish the new version to pub.dev.

2022-10-30 08:25 UTC, SunnyDayDev commented
@mrgnhnt96
I have one more question for you. For the past two years, I haven't touched Flutter at all, except for minimal library support. I'm currently focused on Android native development and KMM, so my Dart/Flutter expertise is fading away.

Do you want to become a library maintainer? Your current changes are totally good, I liked your vision of the project, and, in my opinion, you are the one who can develop the project in right way.

2022-10-30 13:37 UTC, mrgnhnt96 commented
@SunnyDayDev
I'd be happy to! I know that maintaining packages can be hard, especially if you're no longer really using it, even more the language. So I'm more than willing to help you out here!

Transferring the project on pub.dev shouldn't be too hard. You'll need to add me as a publisher, then we can transfer the project to me.

For the repo, you can go into repo settings and click on transfer repo, and you'd put in my username, @mrgnhnt96.